spring:
#  application:
#    name: example
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    datasource:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL
      driver-class-name: org.h2.Driver
      username: sa
  sql:
    init.mode: always